sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t devinhenkel/citest -f Dockerfile.dev .

script:
    - docker run -e CI=true devinhenkel/citest npm run test -- --coverage